version: '3.1'

services:

  dbmessage:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    restart: always
    environment:
      MYSQL_DATABASE: message
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - c:\chat\message\db:/var/lib/mysql
    ports:
      - "33061:3306"
    networks:
      - chat
  
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"
    volumes:
      - c:\chat\rabbit\data:/var/lib/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

networks:
  chat:
    driver: bridge